DROP TABLE IMDB_STAGE.TITLE_EPISODE_EXT;

CREATE TABLE IMDB_STAGE.TITLE_EPISODE_EXT (
  TCONST VARCHAR2(10),
  PARENT_TCONST VARCHAR2(10),
  SEASON_NUMBER VARCHAR2(4ll
  ),
  EPISODE_NUMBER VARCHAR2(6))
  ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER 
    DEFAULT DIRECTORY DIR_IMDB_STAGE
    ACCESS PARAMETERS (
      RECORDS DELIMITED BY NEWLINE
      SKIP 1
      NOBADFILE
      NODISCARDFILE
      NOLOGFILE
      DISABLE_DIRECTORY_LINK_CHECK
      FIELDS TERMINATED BY '\t'
      MISSING FIELD VALUES ARE NULL 
      REJECT ROWS WITH ALL NULL FIELDS
      (
        TCONST CHAR(10),
        PARENT_TCONST CHAR(10),
        SEASON_NUMBER CHAR(4),
        EPISODE_NUMBER CHAR(6))
      )
    LOCATION ('title.episode.csv')
  )
  REJECT LIMIT UNLIMITED
;

