DROP TABLE IMDB_STAGE.TITLE_RATINGS_EXT;

CREATE TABLE IMDB_STAGE.TITLE_RATINGS_EXT (
  TCONST VARCHAR2(10),
  AVERAGE_RATING NUMBER(4,2),
  NUM_VOTES NUMBER(7))
  ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER 
    DEFAULT DIRECTORY DIR_IMDB_STAGE
    ACCESS PARAMETERS (
      RECORDS DELIMITED BY NEWLINE
      SKIP 1
      NOBADFILE
      NODISCARDFILE
      NOLOGFILE
      DISABLE_DIRECTORY_LINK_CHECK
      FIELDS TERMINATED BY '\t'
      MISSING FIELD VALUES ARE NULL 
      REJECT ROWS WITH ALL NULL FIELDS
      (
        TCONST CHAR(10),
        AVERAGE_RATING CHAR(5),
        NUM_VOTES CHAR(7))
      )
    LOCATION ('title.ratings.csv')
  )
  REJECT LIMIT UNLIMITED
;

