DROP TABLE IMDB_STAGE.TITLE_PRINCIPALS_EXT;

CREATE TABLE IMDB_STAGE.TITLE_PRINCIPALS_EXT (
  TCONST VARCHAR2(10),
  ORDERING NUMBER(2),
  NCONST VARCHAR2(10),
  CATEGORY VARCHAR2(20),
  JOB VARCHAR2(500),
  CHARACTERS VARCHAR2(500))
  ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER 
    DEFAULT DIRECTORY DIR_IMDB_STAGE
    ACCESS PARAMETERS (
      RECORDS DELIMITED BY NEWLINE
      SKIP 1
      NOBADFILE
      NODISCARDFILE
      NOLOGFILE
      DISABLE_DIRECTORY_LINK_CHECK
      FIELDS TERMINATED BY '\t'
      MISSING FIELD VALUES ARE NULL 
      REJECT ROWS WITH ALL NULL FIELDS
      (
        TCONST CHAR(10),
        ORDERING CHAR(2),
        NCONST CHAR(10),
        CATEGORY CHAR(20),
        JOB CHAR(500),
        "CHARACTERS" CHAR(500))
      )
    LOCATION ('title.principals.csv')
  )
  REJECT LIMIT UNLIMITED
;

